.Dd Nov 22, 2013
.Dt NAUSEA 1
.Os
.Sh NAME
.Nm nausea
.Nd curses audio visualizer
.Sh SYNOPSIS
.Nm nausea
.Op Fl hcp
.Op Ar fifo
.Sh DESCRIPTION
The
.Nm
program performs a discrete fourier transform and plots the spectrogram
in real time using curses.  The current implementation expects the input
stream to be 44.1kHz, 16-bit little endian and 2 channels.  The default
.Ar fifo
path is
.Pa /tmp/audio.fifo .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
Show usage line.
.It Fl c
Enable color.
.It Fl p
Enable falling peaks.
.El
.Pp
Exposed runtime options:
.Bl -tag -width Ds
.It 1
Select the spectrum visualization.
.It 2
Select the wave visualization.
.It c
Toggle color.
.It p
Toggle falling peaks.
.El
