.Dd Sep 15, 2014
.Dt NAUSEA 1
.Os
.Sh NAME
.Nm nausea
.Nd curses audio visualizer
.Sh SYNOPSIS
.Nm nausea
.Op Fl hcpkl
.Op Fl d Ar num
.Op Ar fifo
.Sh DESCRIPTION
The
.Nm
program performs a discrete fourier transform and plots the spectrogram
in real time using curses.  It can also just display the audio waveform.
The current implementation expects the input stream to be 44.1kHz,
16-bit little endian and 2 channels.  The default
.Ar fifo
path is
.Pa /tmp/audio.fifo .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
Show usage line.
.It Fl d Ar num
Choose a visualization using its number from below.
.It Fl c
Enable color.
.It Fl p
Enable falling peaks in the spectrum visualization.
.It Fl k
Keep state in the fountain visualization.
.It Fl l
Go left in the fountain visualization.
.El
.Pp
Exposed runtime options:
.Bl -tag -width Ds
.It 1
Select the spectrum visualization.
.It 2
Select the wave visualization.
.It 3
Select the fountain visualization.
.It c
Toggle color.
.It p
Toggle falling peaks.
.It k
Toggle keep state.
.It l
Toggle direction.
.El
