# $OpenBSD$

COMMENT =		curses audio visualizer
DISTNAME =		nausea-0.2
CATEGORIES =		audio
HOMEPAGE =		http://git.2f30.org/nausea/
MAINTAINER =		Lazaros Koromilas <lostd@2f30.org>

# BSD
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB =		c curses fftw3 m pthread

MASTER_SITES =		http://git.2f30.org/nausea/snapshot/

LIB_DEPENDS =		math/fftw3

.include <bsd.port.mk>
